### ISSUE TITLE
Metrics filter doesn't support the ${tags_part[X]} config syntax

### ISSUE THREAD

**Issue by jespersoderlund** [fluent/fluent-plugin-prometheus#84]
When trying to use the tag_parts config syntax to add some labels it doesn't work. The following config should add a label "environment" based on the second matching part of the tag.
```
<filter *.* >
  @type prometheus
  <metric>
    name fluentd_input_status_num_records_total
    type counter
    desc The total number of incoming records
    <labels>
      environment ${tag_parts[1]}
      hostname ${hostname}
    </labels>
  </metric>
</filter>
```

**Comment by warmfusion** [comment]
Looks like the RubyPlaceholderExpander could be used instead of the PlaceholderExpander as this expands the tags by default (even if the Ruby feature isn't enabled).

But i'm not sure if I've understood the implementation details well enough to submit at patch with confidence.

Its a shame, as this effectivly becomes a useless plugin for us, as we use the first tag element as an index, with the rest used for other purposes with some very high cardinality (Tens of thousands) which doesn't play well with Prometheus at all.

**Comment by ganmacs** [comment]
https://github.com/fluent/fluent-plugin-prometheus/tree/f8ba16fc18be0da1afe0077d16ba8a1c3b9ff45d#labels
